function DrawVertStructure( obj, ModelTranslation, Color )
%DRAWVERTSTRUCTURE Summary of this function goes here
%   Detailed explanation goes here
    

patch('Faces', obj.Faces, ...
             'Vertices', [obj.Verts(:,1) + ModelTranslation(1) obj.Verts(:,2) + ModelTranslation(2) obj.Verts(:,3) + ModelTranslation(3)], ...
             'FaceVertexCData', Color, ...
             'VertexNormals', obj.Normals, ...
             'FaceColor', Color, ...'none', ... % obj.Color, ... %
             'EdgeColor', [0.5 0.5 0.5], ...%[0 0 1], ...
             'FaceLighting', 'phong',...
             'AmbientStrength', .2, ...
             'DiffuseStrength', .8,...
             'SpecularStrength', .02, ...
             'SpecularExponent', 15,...
             'BackFaceLighting', 'unlit');

end

